# torchtitan Config.toml

[job]
dump_folder = "./outputs"
description = "MusicLlama 3 debug training"
print_args = true
use_for_integration_test = false

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 10
enable_memory_snapshot = false
save_memory_snapshot_folder = "memory_snapshot"

[metrics]
log_freq = 10
disable_color_printing = false
enable_tensorboard = false
save_tb_folder = "tb"
enable_wandb = true
log_target_loss = 16

[model]
name = "llama3"
flavor = "musicllama_2dot5B"
# test tokenizer.model, for debug purpose only
tokenizer_path = "./tests/assets/test_tiktoken.model"
text_token_cnt = 128256
audio_codebook_size = 1024
total_nq = 16
pad_token_id = 128004
eol_token_id = 128255
eos_token_id = 128001

# converters = ["float8"]

[optimizer]
name = "AdamW"
lr = 3e-4
eps = 1e-8

[lr_scheduler]
warmup_steps = 4000  # lr scheduler warm up, normally 20% of the train steps
decay_ratio = 0.08889  # lr scheduler decay ratio, 10% of the stable steps
decay_type = "cosine"
lr_min = 4e-5

[training]
batch_size = 2
gradient_accumulation_steps = 5
seq_len = 8192
bark_window_len = 1024
max_norm = 1.0  # grad norm clipping
steps = 180000
compile = true
dataset = "train_100w_nq16_1111"  # supported datasets: c4_test (2K), c4 (177M)\
dataset_path = ["washed_100w_tokens_randomized_seed1998_valid_seed4619_e607a58f_textaudio_trainval_split4_merged/train_filter0_full", "washed_100w_tokens_randomized_seed1998_valid_seed4619_e607a58f_textaudio_trainval_split4_merged/train_filter1_full", "washed_100w_tokens_randomized_seed1998_valid_seed4619_e607a58f_textaudio_trainval_split4_merged/train_filter2_full", "washed_100w_tokens_randomized_seed1998_valid_seed4619_e607a58f_textaudio_trainval_split4_merged/train_filter3_full"]
dataset_sample_ratios = [1,1,1,1]
pred_task_ratios = [6,6,3,2,1,1,1,1,1,1,1,1,1,1,1,1]
target_seed = 1337
window_seed = 1999

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
fsdp_reshard_after_forward = "default" # default / never / always
tensor_parallel_degree = 1
enable_async_tensor_parallel = false
pipeline_parallel_degree = 1
context_parallel_degree = 1

[checkpoint]
enable_checkpoint = true
folder = "music_bark_2dot5b_gb240_mb2_ga5_flexattn"
interval = 500
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled"  # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = "none"  # ["none", "selective", "full"]
selective_ac_option = "op"  # "int" = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_fsdp_float8_all_gather = false
precompute_float8_dynamic_scale_for_fsdp = false
filter_fqns = ["output"]
